=== mirkoviviani76/gestcoll/GestColl/Xml_schemas/configurations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
targetNamespace="http://gestColl/configurations" elementFormDefault="qualified" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:tns="http://gestColl/configurations">

	<xsd:annotation>
		<xsd:documentation>Configurazioni</xsd:documentation>
		<xsd:appinfo>v.0.1</xsd:appinfo>
	</xsd:annotation>

	<xsd:complexType name="dirs">
		<xsd:annotation>
			<xsd:documentation>Tipo che definisce un elenco di dirs</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element minOccurs="1" maxOccurs="1" name="base_dir" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="backup_dir" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="biblioteca_dir" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="html_dir" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="latex_dir" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="qr_dir" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="img_dir" type="xsd:string" />
		</xsd:all>
	</xsd:complexType>

	<xsd:complexType name="data">
		<xsd:annotation>
			<xsd:documentation>Tipo che definisce un elenco di dati</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element minOccurs="1" maxOccurs="1" name="contenitori_xml" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="contatti_xml" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="links_xml" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="biblio_xml" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="collezione_xml" type="xsd:string" />
		</xsd:all>
	</xsd:complexType>

	<xsd:complexType name="logs">
		<xsd:annotation>
			<xsd:documentation>Tipo che definisce un elenco di logs</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element minOccurs="1" maxOccurs="1" name="history_log" type="xsd:string" />
			<xsd:element minOccurs="1" maxOccurs="1" name="log_property" type="xsd:string" />
		</xsd:all>
	</xsd:complexType>

	
	<xsd:complexType name="configuration">
		<xsd:sequence>
			<xsd:element maxOccurs="1" minOccurs="1" name="dirs" type="tns:dirs"/>
			<xsd:element maxOccurs="1" minOccurs="1" name="data" type="tns:data"/>
			<xsd:element maxOccurs="1" minOccurs="1" name="logs" type="tns:logs"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required" />
	</xsd:complexType>
	


	<xsd:element name="configurations">
		<xsd:annotation>
			<xsd:documentation>Configurazioni per GestColl</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="1" name="configuration" type="tns:configuration"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== mirkoviviani76/gestcoll/GestColl/extra/configurations.xml
<?xml version="1.0" encoding="UTF-8"?>
<configurations xmlns="http://gestColl/configurations"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://gestColl/configurations ./configurations.xsd">
>
	<configuration id="windows">
		<dirs>
				<base_dir>D:/mieProve/Java/GestColl/GestColl</base_dir>
				<monete_dir>D:/mieProve/Java/GestColl/Monete</monete_dir>
				<backup_dir>D:/mieProve/Java/GestColl/Backup</backup_dir>
				<biblioteca_dir>D:/mieProve/Java/GestColl/Biblioteca</biblioteca_dir>
				<html_dir>D:/mieProve/Java/GestColl/Reports/Html</html_dir>
				<latex_dir>D:/mieProve/Java/GestColl/Reports/LaTeX</latex_dir>
				<qr_dir>D:/mieProve/Java/GestColl/Reports/QR</qr_dir>
		</dirs>
		<data>
				<contenitori_xml>D:/mieProve/Java/GestColl/bin/data/contenitori.xml</contenitori_xml>
				<contatti_xml>D:/mieProve/Java/GestColl/bin/data/contatti.xml</contatti_xml>
				<links_xml>D:/mieProve/Java/GestColl/bin/data/links.xml</links_xml>
				<biblio_xml>D:/mieProve/Java/GestColl/bin/data/biblioteca.xml</biblio_xml>
		</data>
		<logs>
				<history_log>D:/mieProve/Java/GestColl/bin/data/history.txt</history_log>
				<log_property>D:/mieProve/Java/GestColl/bin/data/myLoggingProperties.properties</log_property>
		</logs>
	</configuration>
	<configuration id="linux">
		<dirs>
				<base_dir>/dati/Collezione/bin</base_dir>
				<monete_dir>/dati/Collezione/Monete</monete_dir>
				<backup_dir>/dati/Collezione/Backup</backup_dir>
				<biblioteca_dir>/dati/Collezione/Biblioteca</biblioteca_dir>
				<html_dir>/dati/Collezione/Reports/Html</html_dir>
				<latex_dir>/dati/Collezione/Reports/LaTeX</latex_dir>
				<qr_dir>/dati/Collezione/Reports/QR</qr_dir>
		</dirs>
		<data>
				<contenitori_xml>/dati/Collezione/bin/data/contenitori.xml</contenitori_xml>
				<contatti_xml>/dati/Collezione/bin/data/contatti.xml</contatti_xml>
				<links_xml>/dati/Collezione/bin/data/links.xml</links_xml>
				<biblio_xml>/dati/Collezione/bin/data/biblioteca.xml</biblio_xml>
		</data>
		<logs>
				<history_log>/dati/Collezione/bin/data/history.txt</history_log>
				<log_property>/dati/Collezione/bin/data/myLoggingProperties.properties</log_property>
		</logs>
	</configuration>
</configurations>
